name: ubuntu

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install xsltproc

      - name: XSD documentation generation
        run: |
          make

      - uses: actions/upload-artifact@v4.1.8
        with:
          name: published-ubuntu
          path: docs

      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Run the Ant report target
        run: ant -noinput -buildfile build.xml report

  deploy-gh-pages:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2

    - uses: actions/download-artifact@v4.1.8
      with:
        name: published-ubuntu
        path: docs

    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
        force_orphan: true
        user_name: ${{ github.actor }}
        user_email: ${{ format('{0}@users.noreply.github.com', github.actor) }}
        commit_message: "${{ format('Deploy to GitHub Pages: {0}', github.sha) }}"
